name: Update README Daily

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

  permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run update script
        run: python scripts/update_readme.py

      - name: Commit changes
        run: |
          git config --global user.name "WahyuSatrio505"
          git config --global user.email "wahyuusatriowibowo@gmail.com"
          git add .
          git commit -m "auto update $(date)" || echo "No changes"
          git push
